### ISSUE TITLE
Porting from jnetpcap v1 to v2: PcapIf.getHardwareAddress() (question)

### ISSUE THREAD

**Issue by arisona** [slytechs-repos/jnetpcap-wrapper#48]
I'm porting v1 code to v2, and I'm sending raw ethernet frames using Pcap.sendPacket / Pcap.inject. In my old code, I was using PcapIf.getHardwareAddress() to determine the source mac address, but in v2, this seems to be gone.

What's the recommended way of filling in the source mac address when assembling an ethernet frame to be sent?

**Comment by slytechs-repos** [comment]
That method wasn't ported, you have to iterate over the `PcapIf` addresses to find the HW address entry, but I will put that back into v2. I'm working on the issue #47 right now, but will add that into the SNAPSHOT release.

jNetworks is on Maven central and sonatype snapshot server now, so you will be able to download the snapshot with the bug fix and I will follow up with the `gethardwareAddress()` method as well. That should be put back in v2 for backward compatibility.

**Comment by arisona** [comment]
Thanks for the feedback. I wasn't sure about PcapIf since addresses don't seem to be accessible. Also not sure if the enet address will actually show up in there. But first things first, let's see about #47 - I have checked out the develop branch and can pull directly and test once a fix is in.

**Comment by slytechs-repos** [comment]
Yes, that is also an alternative. In v1 this was solved using a custom C function [`mac_addr_sys`](https://github.com/slytechs-repos/jnetpcap-legacy/blob/main/src/c/mac_addr_sys.c) which was called from java via JNI to retrieve from a sock_addr structure.

```
/* implementation for darwin/MacOS */
#ifdef DARWIN
	struct ifaddrs *ifa = NULL;
	struct sockaddr_dl* dl;

	getifaddrs(&ifa);

	while (ifa != NULL) {
		dl = (struct sockaddr_dl*)ifa->ifa_addr;
		if (dl->sdl_nlen > 0 && strncmp(dev, dl->sdl_data, dl->sdl_nlen) == 0) {
			bcopy((u_char *)LLADDR(dl), addr, 6);
			return 0;
		} else {
			ifa = ifa->ifa_next;
		}
	}

#endif
```

**Comment by slytechs-repos** [comment]
I added the PcapIf::getHardwareAddress method. Committed to branch for now.

**Comment by arisona** [comment]
LGTM. One suggestion: in terms of naming jnetpcap conventions, maybe just call it "hardwareAddress()"?

**Comment by slytechs-repos** [comment]
You are rights. I changed it to `PcapIf::hardwareAddress `. V2 is not 100% API backward compatible with v1 anyhow, might as well stick with the better convention.

I also added -Dorg.jnetpcap.sockaddr.bsd=true flag. Otherwise it does its heuristics thing. 

As to the SNAPSHOT dev release.  You need to add the following to your `pom.xml` file 
```
  <repositories>
    <!-- Add to get the latest Sly Techs' development SNAPSHOT artifacts, 
         ie. com.slytechs.jnet.jnetpcap:jnetpcap-api:0.10.0-SNAPSHOT -->
    <repository>
      <id>oss.sonatype.org-snapshot</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
```
To add the snapshot server/repository. Then the maven coordinates for jnetpcap have changed, as I'm reoganizing all modules to fit properly for a steady Maven central release schedule. New coordinate is `com.slytechs.jnet.jnetpcap:jnetpcap-wrapper:2.1.0-SNAPSHOT` to get the 2.1.0 (API changed) snapshots.

**Comment by arisona** [comment]
I can confirm this all works nicely on a Raspberry Pi 64 bit. All I had to do was to use

`-Dorg.jnetpcap.libpcap.file=/usr/lib/aarch64-linux-gnu/libpcap.so.0.8`

Might be kind of nice to add 

/usr/lib/aarch64-linux-gnu to DEFAULT_JAVA_LIBRARY_PATH in Pcap.java, but not a big deal.

So happy about libnetpcap v2, thanks for getting this to us!

**Comment by slytechs-repos** [comment]
I added one more subclass for `SockAddr` for AF_LINK so we get nice output as its used heavily on MacOS and looks good using  PcapIf::toString on MacOS.

If you could have one more look before I merge all the changes into dev branch and close out the 2 tickets.

![image](https://github.com/slytechs-repos/jnetpcap-wrapper/assets/116599131/ae398fbe-29fb-435d-8fea-6e9bba26e5f0)

![image](https://github.com/slytechs-repos/jnetpcap-wrapper/assets/116599131/394c11cc-6e85-401a-8f60-1ddd8bbca97d)

**Comment by arisona** [comment]
Had a quick look, AF_LINK works for me!

**Comment by slytechs-repos** [comment]
Thank you for verifying. 

I have merged all changes into the [**develop**](https://github.com/slytechs-repos/jnetpcap-wrapper/tree/develop) branch and will close out this ticket and associated **bug-47** branch. 

You will find these changes in  `com.slytechs.jnet.jnetpcap:jnetpcap-wrapper:2.1.0` SNAPSHOT and main release.

**Comment by slytechs-repos** [comment]
One final comment, all the changes are in the jnetpcap-wrapper v2.1.0 release is on Maven Central servers now.

https://mvnrepository.com/artifact/com.slytechs.jnet.jnetpcap/jnetpcap-wrapper
